/* automatically generated by rust-bindgen 0.72.1 */

pub const MLDSA65_SECRETKEYBYTES: u32 = 4032;
pub const MLDSA65_PUBLICKEYBYTES: u32 = 1952;
pub const MLDSA65_BYTES: u32 = 3309;
pub const MLDSA65_SEEDBYTES: u32 = 32;
pub const MLDSA65_CRHBYTES: u32 = 64;
pub const MLDSA65_TRBYTES: u32 = 64;
pub const MLDSA65_RNDBYTES: u32 = 32;
pub const MLD_ERR_FAIL: i32 = -1;
pub const MLD_ERR_OUT_OF_MEMORY: i32 = -2;
pub const MLD_ERR_RNG_FAIL: i32 = -3;
pub const MLD_ERR_SIGN_ATTEMPTS_EXHAUSTED: i32 = -4;
pub const MLD_ERR_SIGNING_PAUSED: i32 = -5;
pub const MLD_ERR_INVALID_SIGNATURE: i32 = -6;
pub const MLD_ERR_INVALID_KEY: i32 = -7;
pub const MLD_ERR_PCT_FAIL: i32 = -8;
pub const MLD_ERR_INVALID_ARG: i32 = -9;
unsafe extern "C" {
    pub fn mldsa65_keypair_internal(
        pk: *mut u8,
        sk: *mut u8,
        seed: *const u8,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn mldsa65_signature_internal(
        sig: *mut u8,
        m: *const u8,
        mlen: usize,
        pre: *const u8,
        prelen: usize,
        rnd: *const u8,
        sk: *const u8,
        externalmu: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn mldsa65_verify_internal(
        sig: *const u8,
        m: *const u8,
        mlen: usize,
        pre: *const u8,
        prelen: usize,
        pk: *const u8,
        externalmu: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
